### ISSUE TITLE
add pressure_advance_smooth_time

### ISSUE THREAD

**Issue by adiekwisch** [jjgraphix/KlipperSettingsPlugin#1]
First of all, thank you for sharing the plugin! It is very helpful when working with multiple kinds of filament on the same printer.

May I suggest adding the parameter pressure_advance_smooth_time to the list of settings as well? I know it is usually not changed that much, but I found some filaments benefit from having it modified. 

Thanks for your consideration and keep up the good work :)

**Comment by jjgraphix** [comment]
No problem, glad it's helping. Adding smooth time is on my list and I'm aiming to include the feature in the next major update. Since it doesn't make much sense to control it per line type it'll be a single setting you can set for different filament.

Thanks for the feedback.
