### ISSUE TITLE
STEP_DELTA unable to be negative in tuning tower settings.

### ISSUE THREAD

**Issue by SUAFT-Chammy** [jjgraphix/KlipperSettingsPlugin#4]
Tuning tower settings in the plugin don't allow negative numbers for STEP_DELTA, when a negative number can be used just fine when executing the command normally.
![Screenshot 2022-12-30 at 2 04 36 PM](https://user-images.githubusercontent.com/121691480/210104648-d6109535-3234-4148-9801-279f60475d6c.png)
![Screenshot 2022-12-30 at 2 12 21 PM](https://user-images.githubusercontent.com/121691480/210104683-c9610405-d80d-4c3a-824f-be7f5ca9d823.png)

**Comment by jjgraphix** [comment]
Thank you for the feedback, this is fixed in the next version. I'm finally having some time to work more on this and it will be uploaded by the end of the week.

If you have another other suggestion, let me know and I may be able to squeeze it in if it isn't already.
