### ISSUE TITLE
Cannot set retraction settings per material

### ISSUE THREAD

**Issue by leoshusar** [jjgraphix/KlipperSettingsPlugin#5]
I wanted to set different retraction distance and speed per material using MaterialSettings plugin and these values cannot be set, because they are not defined as `settable_per_extruder` nor they have `resolve` function.

Would it be possible to change them?

Thank you!

**Comment by jjgraphix** [comment]
The latest version now includes extensive multi-extruder support for firmware retraction. The default values have been linked to Cura's retraction values so they can be easily saved in profiles without the need for additional plugins. 

This should accomplish everything you're looking for and more :)
